version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: fullstack-project-db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    depends_on:
      - db
    build: ./backend/spring-boot-app
    ports:
      - "8080:8080"
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fullstack-project-db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: appuser
    networks:
      - app-network
    restart: on-failure

  frontend:
    build: ./frontend/angular-app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:

